# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: missionRequest.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14missionRequest.proto\x12\x05\x63olav\"\xa9\x06\n\x0eMissionRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12,\n\x06vessel\x18\x03 \x01(\x0b\x32\x1c.colav.MissionRequest.Vessel\x12\x32\n\rinit_position\x18\x04 \x01(\x0b\x32\x1b.colav.MissionRequest.Point\x12\x39\n\rgoal_position\x18\x05 \x01(\x0b\x32\".colav.MissionRequest.GoalWaypoint\x1a(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\xd9\x03\n\x06Vessel\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x35\n\x04type\x18\x02 \x01(\x0e\x32\'.colav.MissionRequest.Vessel.VesselType\x12\x43\n\x0b\x63onstraints\x18\x03 \x01(\x0b\x32..colav.MissionRequest.Vessel.VesselConstraints\x12=\n\x08geometry\x18\x04 \x01(\x0b\x32+.colav.MissionRequest.Vessel.VesselGeometry\x1a\x89\x01\n\x11VesselConstraints\x12\x18\n\x10max_acceleration\x18\x03 \x01(\x02\x12\x18\n\x10max_deceleration\x18\x04 \x01(\x02\x12\x14\n\x0cmax_velocity\x18\x05 \x01(\x02\x12\x14\n\x0cmin_velocity\x18\x06 \x01(\x02\x12\x14\n\x0cmax_yaw_rate\x18\x07 \x01(\x02\x1a\x42\n\x0eVesselGeometry\x12\x0b\n\x03loa\x18\x01 \x01(\x02\x12\x0c\n\x04\x62\x65\x61m\x18\x02 \x01(\x02\x12\x15\n\rsafety_radius\x18\x03 \x01(\x02\"7\n\nVesselType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\r\n\tHYDROFOIL\x10\x01\x12\t\n\x05OTHER\x10\x02\x1aT\n\x0cGoalWaypoint\x12-\n\x08position\x18\x01 \x01(\x0b\x32\x1b.colav.MissionRequest.Point\x12\x15\n\rsafety_radius\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'missionRequest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MISSIONREQUEST']._serialized_start=32
  _globals['_MISSIONREQUEST']._serialized_end=841
  _globals['_MISSIONREQUEST_POINT']._serialized_start=239
  _globals['_MISSIONREQUEST_POINT']._serialized_end=279
  _globals['_MISSIONREQUEST_VESSEL']._serialized_start=282
  _globals['_MISSIONREQUEST_VESSEL']._serialized_end=755
  _globals['_MISSIONREQUEST_VESSEL_VESSELCONSTRAINTS']._serialized_start=493
  _globals['_MISSIONREQUEST_VESSEL_VESSELCONSTRAINTS']._serialized_end=630
  _globals['_MISSIONREQUEST_VESSEL_VESSELGEOMETRY']._serialized_start=632
  _globals['_MISSIONREQUEST_VESSEL_VESSELGEOMETRY']._serialized_end=698
  _globals['_MISSIONREQUEST_VESSEL_VESSELTYPE']._serialized_start=700
  _globals['_MISSIONREQUEST_VESSEL_VESSELTYPE']._serialized_end=755
  _globals['_MISSIONREQUEST_GOALWAYPOINT']._serialized_start=757
  _globals['_MISSIONREQUEST_GOALWAYPOINT']._serialized_end=841
# @@protoc_insertion_point(module_scope)
