name: colav_protobuf CI/CD
run-name: ${{ github.actor }} is testing colav_protobuf pypi pkg 🚀

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    release:
        types: [created, prereleased, published]

jobs:
    test: 
        name: Run Tests
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            
            - name: Install build tools
              run: | 
                pip install build twine setuptools

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Build colav_protobuf pkg
              run: |
                python -m build
        
            - name: publish to pypi
              if: github.event_name == 'release'
              env: 
                PYPI_USERNAME: __token__
                PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: twine upload dist/* -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}" --non-interactive
